import {createToolHandler,viewCommentary} from './live-actions.js';
export function setupLive({el,api,execute,toast,available,recording,mount=document.body}){
 let peer,channel,stream,timer,closing,active=false,connecting=false,generation=0,executing=false,lastCommentary;
 const panel=el('aside',{class:'live-panel',hidden:'','aria-label':'GPT Live Sprachcall'}),status=el('span',{role:'status'},'Bereit'),log=el('div',{class:'live-log','aria-live':'polite'}),audio=el('audio',{controls:'',autoplay:''});
 const button=el('button',{class:'live-start',onClick:start},'◉ GPT Live'),stop=el('button',{onClick:end,disabled:''},'Call beenden');
 const typed=el('input',{placeholder:'Optional: Nachricht an Live','aria-label':'Nachricht an Live'});const form=el('form',{onSubmit:e=>{e.preventDefault();const text=typed.value.trim();if(!active||!text)return;append('Du',text);send({type:'response.item.create',event_id:crypto.randomUUID(),item:{type:'message',role:'user',content:[{type:'input_text',text}]}});send({type:'response.create',event_id:crypto.randomUUID()});typed.value=''}},typed,el('button',{type:'submit'},'Senden'));
 panel.append(form);panel.append(el('div',{class:'live-heading'},status,el('button',{onClick:()=>panel.classList.toggle('compact'),'aria-label':'Call-Protokoll umschalten'},'↕'),stop),audio,log);mount.append(button);document.body.append(panel);
 function append(label,text){const row=el('div',{},el('b',{},label+' · '),text);log.append(row);while(log.children.length>60)log.firstChild.remove();log.scrollTop=log.scrollHeight;return row}
 function send(event){if(active&&channel?.readyState==='open')channel.send(JSON.stringify(event))}
 function comment(result){const content=viewCommentary(result);if(content&&content!==lastCommentary){lastCommentary=content;send({type:'session.commentary.append',event_id:crypto.randomUUID(),delegation_id:null,content})}}
 function cleanup(){generation++;active=false;connecting=false;clearTimeout(timer);clearTimeout(closing);stream?.getTracks().forEach(t=>t.stop());const old=channel;channel=null;old?.close();peer?.close();peer=null;audio.srcObject=null;button.disabled=false;stop.disabled=true;button.textContent='◉ GPT Live'}
 function end(){if(!active){cleanup();status.textContent='Call beendet';return}active=false;stream?.getTracks().forEach(t=>t.enabled=false);stop.disabled=true;status.textContent='Call wird beendet …';if(channel?.readyState==='open')channel.send(JSON.stringify({type:'session.close'}));closing=setTimeout(()=>{cleanup();status.textContent='Call beendet · Abschluss nicht bestätigt'},15000)}
 async function start(){if(active||connecting)return;if(recording()){toast('Bitte zuerst das Diktat beenden.');return}if(!available()){toast('GPT Live wird noch eingerichtet.');return}connecting=true;button.disabled=true;stop.disabled=false;panel.hidden=false;log.replaceChildren();lastCommentary=null;status.textContent='Mikrofon verbinden …';const current=++generation;
 try{const connection=peer=new RTCPeerConnection();connection.addEventListener('track',e=>{audio.srcObject=new MediaStream([e.track]);audio.play().catch(()=>status.textContent='Bitte im Audioplayer auf Play tippen')});const microphone=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(current!==generation){microphone.getTracks().forEach(t=>t.stop());return}stream=microphone;stream.getTracks().forEach(t=>connection.addTrack(t,stream));const events=channel=connection.createDataChannel('oai-events');const runAction=async action=>{if(!active||current!==generation)throw Error('Call beendet.');append('Aktion',action.action);executing=true;try{const result=await execute(action);append(result.error?'Fehler':'Ausgeführt',result.error||action.action);if(['review','next','previous','open','done','reply','later'].includes(action.action))comment(result);return result}finally{executing=false}};const handle=createToolHandler(runAction,send);let transcript,lastType='';
 events.addEventListener('message',({data})=>{if(current!==generation)return;try{const e=JSON.parse(data);if(e.type==='session.started'){active=true;connecting=false;clearTimeout(timer);status.textContent='GPT Live verbunden';button.textContent='◉ Call läuft';timer=setTimeout(end,20*60000);send({type:'session.instructions.append',event_id:crypto.randomUUID(),delegation_id:null,content:'Die Oberfläche öffnet jetzt den aktuellen bzw. ersten Chat und liefert dir die bestätigten Chat-Daten zum Vorlesen. Lies den Titel und fasse das neueste Agent-Ergebnis in höchstens zwei Sätzen zusammen, erwähne Fehler und offene Fragen. Warte dann auf den Nutzer mündliche Anweisung. Nach einem Chatwechsel erneut zusammenfassen. Keine Bestätigung per Tippen verlangen. Der Call endet spätestens nach 20 Minuten.'});runAction({action:'review'}).catch(e=>append('Fehler',e.message))}else if(e.type==='session.closed'){cleanup();status.textContent='Call beendet'}else if(e.type==='error'){append('Fehler',e.error?.message||'Live-Fehler')}else if(['session.input_transcript.delta','session.output_transcript.delta'].includes(e.type)){if(lastType!==e.type){transcript=append(e.type.includes('input')?'Du':'GPT Live','');lastType=e.type}transcript.append(document.createTextNode(e.delta||''));log.scrollTop=log.scrollHeight}handle(e)}catch{append('Fehler','Ungültiges Live-Ereignis')}});
 events.addEventListener('close',()=>{if(current===generation){cleanup();status.textContent='Verbindung beendet · Abschluss nicht bestätigt'}});connection.addEventListener('connectionstatechange',()=>{if(current===generation&&['failed','disconnected'].includes(connection.connectionState)){cleanup();status.textContent='Verbindung unterbrochen'}});
 await connection.setLocalDescription(await connection.createOffer());if(connection.iceGatheringState!=='complete')await new Promise((resolve,reject)=>{const limit=setTimeout(()=>{connection.removeEventListener('icegatheringstatechange',check);reject(Error('Netzwerkverbindung dauert zu lange.'))},10000);function check(){if(connection.iceGatheringState==='complete'){clearTimeout(limit);connection.removeEventListener('icegatheringstatechange',check);resolve()}}connection.addEventListener('icegatheringstatechange',check);check()});if(current!==generation)return;
 const result=await api('live-session',{sdp:connection.localDescription.sdp});if(current!==generation)return;await connection.setRemoteDescription({type:'answer',sdp:result.transport.sdp});if(!active)timer=setTimeout(()=>{cleanup();status.textContent='GPT Live konnte nicht verbunden werden'},30000);
 }catch(e){if(current!==generation)return;cleanup();status.textContent=e.name==='NotAllowedError'?'Bitte Mikrofonzugriff für die App erlauben.':e.message;toast(status.textContent)}}
 const close=()=>{if(channel?.readyState==='open')channel.send(JSON.stringify({type:'session.close'}));cleanup()};window.addEventListener('pagehide',close);return {isActive:()=>active||connecting,context:result=>{if(active&&!executing)comment(result)},destroy:()=>{close();window.removeEventListener('pagehide',close);button.remove();panel.remove()}};
}
